### ISSUE TITLE
Requests can work

### ISSUE THREAD

**Issue by Jacoblightning** [GabeMillikan/infinite-craft-explorer#2]
Requests can work with Cloudflare (sort of). If you use [Curl Cffi](https://pypi.org/project/curl-cffi/) and use `from curl_cffi import requests`. That requests module will work with almost anything. There is a write-up on it [here](https://rentry.org/CloudflareRequests).

**Comment by GabeMillikan** [comment]
Thanks for the idea, I have updated the repository to not use Selenium. I did have to prompt users to copy/paste networking information out of their browser, though. I still believe that this is easier than getting selenium to work correctly.
