### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SpyC0der77** [GabeMillikan/infinite-craft-explorer#3]
I want to use this as an api to see what merging two things on infinite craft makes. Can you make the database open source?

**Comment by GabeMillikan** [comment]
Tracking the database would be problematic, but here's my (incomplete) local database containing 47,323 pairings of 7,252 unique elements.

[cache.zip](https://github.com/user-attachments/files/16830928/cache.zip)

**Comment by SpyC0der77** [comment]
Why would it be problematic?

**Comment by GabeMillikan** [comment]
I don't want to upload the database every time I commit a change, and I suspect this is true for most people who want to use this repository.

I have added a [Releases](https://github.com/GabeMillikan/infinite-craft-explorer/releases) tab, where I will periodically upload larger versions of the database. I just uploaded a 10,000 element / 82,000 pair database.
