### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by Roddynotrich** [GabeMillikan/infinite-craft-explorer#4]
Does it not save on infinite craft? It seems as though all its doing is making the combos and sending it to the SQLite but not doing anything on the actual site. Thank you.

**Comment by GabeMillikan** [comment]
Correct, it does not save anything on the actual site. That was never the intention. It should be possible to create a function in the program that allows you to execute some javascript in your browser that would update the local storage to include all of the elements. I may implement this feature.

**Comment by GabeMillikan** [comment]
I've added a feature to add the elements back into the browser! See how, [here](https://github.com/GabeMillikan/infinite-craft-explorer?tab=readme-ov-file#output).
